---
- name: Update AMI for EKS Cluster
  hosts: localhost
  gather_facts: False
  vars:
    region: 'us-east-1'
    cluster_name: 'poojit'
    nodegroup_name: 'private-nodes'
    kubernetes_version: '1.27'
    instance_type: 't3.large'
    security_groups: 'sg-08f57dd50a2699b45'
    key_name: 'mykey'

  tasks:
    - name: Get the latest EKS-optimized AMI ID
      command: >
        aws ssm get-parameter --region {{ region }} --name /aws/service/eks/optimized-ami/{{ kubernetes_version }}/amazon-linux-2/recommended/image_id --query 'Parameter.Value' --output text
      register: ami_description
      changed_when: False

    - name: Extract the AMI ID
      set_fact:
        new_ami_id: "{{ ami_description.stdout }}"

    - name: Create a new launch configuration with the new AMI
      command: >
        aws autoscaling create-launch-configuration --launch-configuration-name {{ nodegroup_name }}-new --image-id {{ new_ami_id }} --instance-type {{ instance_type }} --security-groups {{ security_groups }} --key-name {{ key_name }}
      register: new_launch_configuration

    - name: Update the Auto Scaling Group to use the new launch configuration
      command: >
        aws autoscaling update-auto-scaling-group --auto-scaling-group-name {{ asg_name }} --launch-configuration-name {{ asg_name }}-new

  #  - name: Optionally, you can delete the old launch configuration here
