---
- name: Update AMI for EKS Cluster
  hosts: localhost
  gather_facts: False
  vars:
    region: 'us-east-1'
    cluster_name: 'poojit'
    kubernetes_version: '1.27'

  tasks:
    - name: Get the latest EKS-optimized AMI ID
      command: >
        aws ssm get-parameter --region {{ region }} --name /aws/service/eks/optimized-ami/{{ kubernetes_version }}/amazon-linux-2/recommended/image_id --query 'Parameter.Value' --output text
      register: ami_description
      changed_when: False

    - name: Extract the AMI ID
      set_fact:
        new_ami_id: "{{ ami_description.stdout }}"

    - name: Get the current launch template version
      command: >
        aws eks describe-nodegroup --region {{ region }} --cluster-name {{ cluster_name }} --nodegroup-name {{ cluster_name }}-nodegroup
      register: nodegroup_description
      changed_when: False

    - name: Extract launch template ID and version
      set_fact:
        launch_template_id: "{{ (nodegroup_description.stdout | from_json).nodegroup.launchTemplate.id }}"
        launch_template_version: "{{ (nodegroup_description.stdout | from_json).nodegroup.launchTemplate.version }}"

    - name: Create a new launch template version with the new AMI
      command: >
        aws ec2 create-launch-template-version --region {{ region }} --launch-template-id {{ launch_template_id }} --version-description "Updated AMI" --launch-template-data "{\"imageId\":\"{{ new_ami_id }}\"}"
      register: new_launch_template_version

    - name: Extract the new launch template version number
      set_fact:
        new_version_number: "{{ (new_launch_template_version.stdout | from_json).launchTemplateVersion.versionNumber }}"

    - name: Update the EKS node group to use the new launch template version
      command: >
        aws eks update-nodegroup-version --region {{ region }} --cluster-name {{ cluster_name }} --nodegroup-name {{ cluster_name }}-nodegroup --launch-template version={{ new_version_number }} 
