---
- name: Update AMI for EKS Cluster
  hosts: localhost
  gather_facts: False
  vars:
    region: 'us-east-1'
    cluster_name: 'poojit'
    nodegroup_name: 'private-nodes'
    kubernetes_version: '1.27'

  tasks:
    - name: Get the latest EKS-optimized AMI ID
      command: >
        aws ssm get-parameter --region {{ region }} --name /aws/service/eks/optimized-ami/{{ kubernetes_version }}/amazon-linux-2/recommended/image_id --query 'Parameter.Value' --output text
      register: ami_description
      changed_when: False

    - name: Extract the AMI ID
      set_fact:
        new_ami_id: "{{ ami_description.stdout }}"

    - name: Get the Auto Scaling Group name
      set_fact:
        asg_name: "eks-private-nodes-70c4d155-2565-d715-61e6-5aac6134020b"

    - name: Create a new launch configuration with the new AMI
      command: >
        aws autoscaling create-launch-configuration --launch-configuration-name {{ asg_name }}-new --image-id {{ new_ami_id }} --instance-type t3.large
      register: new_launch_configuration

    - name: Update the Auto Scaling Group to use the new launch configuration
      command: >
        aws autoscaling update-auto-scaling-group --auto-scaling-group-name {{ asg_name }} --launch-configuration-name {{ asg_name }}-new

    - name: Optionally, you can delete the old launch configuration here
