---
- name: Update AMI for EKS Cluster
  hosts: localhost
  gather_facts: False
  vars:
    region: 'us-east-1'
    cluster_name: 'poojit'
    kubernetes_version: '1.27'

  tasks:
    - name: Get the latest EKS-optimized AMI ID
      amazon.aws.ec2_ami_info:
        region: "{{ region }}"
        filters:
          name: "amazon-eks-node-{{ kubernetes_version }}-v*"
          architecture: x86_64
          virtualization-type: hvm
          root-device-type: ebs
      register: ami_info

    - name: Extract the AMI ID
      set_fact:
        new_ami_id: "{{ ami_info.images[0].image_id }}"

    - name: Get details about the EKS cluster
      community.aws.aws_eks_info:
        name: "{{ cluster_name }}"
        region: "{{ region }}"
      register: eks_info

    - name: Extract launch template ID
      set_fact:
        launch_template_id: "{{ eks_info.clusters[0].node_groups[0].launch_template.id }}"

    - name: Create a new launch template version with the new AMI
      amazon.aws.ec2_launch_template:
        launch_template_name: "{{ launch_template_id }}"
        image_id: "{{ new_ami_id }}"
        region: "{{ region }}"
      register: new_launch_template_version

    - name: Update the EKS node group to use the new launch template version
      command: >
        aws eks update-nodegroup-version --region {{ region }} --cluster-name {{ cluster_name }} --nodegroup-name {{ cluster_name }}-nodegroup --launch-template version={{ new_launch_template_version.latest_version_number }}
